---
chdir: /srv/tachyon/engine
environment: production
address: 0.0.0.0
port: 3000
timeout: 121
log: log/thin.log
pid: tmp/pids/thin.pid
max_conns: 1024
max_persistent_conns: 512
require: []
wait: 120
daemonize: true
threaded: true
servers: 1



